PASS: tests/errors/syn7.kt
PASS: tests/errors/lex_test42.kt
PASS: tests/errors/lex_test12.kt
PASS: tests/errors/syn2.kt
PASS: tests/errors/syn3.kt
PASS: tests/errors/lex_test53.kt
FAIL: tests/errors/syn8.kt
Expected Error, but got:
Processing file: tests/errors/syn8.kt
DEBUG: Entering node: functionDeclaration (prod: 327) at line 5, scope: 0x556559c1bdd0
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'outer' has scope pointer: 0x556559c1bb10
DEBUG: Entering node: outer (prod: 396) at line 0, scope: 0x556559c1bb10
DEBUG: Entering node: functionValueParameters (prod: 108) at line 1, scope: 0x556559c1bb10
DEBUG: Entering node: block (prod: 111) at line 5, scope: 0x556559c1bb10
DEBUG: Entering node: functionDeclaration (prod: 327) at line 4, scope: 0x556559c1bb10
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'inner' has scope pointer: 0x556559c1bdd0
DEBUG: Entering node: inner (prod: 396) at line 0, scope: 0x556559c1bdd0
DEBUG: Entering node: functionValueParameters (prod: 108) at line 2, scope: 0x556559c1bdd0
DEBUG: Entering node: block (prod: 111) at line 4, scope: 0x556559c1bdd0
DEBUG: Entering node: functionCall (prod: 122) at line 4, scope: 0x556559c1bdd0
DEBUG: Entering node: println (prod: 396) at line 0, scope: 0x556559c1bdd0
DEBUG: Entering node: expressionList (prod: 116) at line 3, scope: 0x556559c1bdd0
DEBUG: Entering node: StringLiteral (prod: 395) at line 3, scope: 0x556559c1bdd0
DEBUG: Entering node: "Nested function" (prod: 395) at line 0, scope: 0x556559c1bdd0
No errors

FAIL: tests/errors/syn6.kt
Expected Error, but got:
Processing file: tests/errors/syn6.kt
DEBUG: Entering node: functionDeclaration (prod: 327) at line 4, scope: 0x559f3a763590
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'missingBraces' has scope pointer: 0x559f3a763590
DEBUG: Entering node: missingBraces (prod: 396) at line 0, scope: 0x559f3a763590
DEBUG: Entering node: functionValueParameters (prod: 108) at line 1, scope: 0x559f3a763590
DEBUG: Entering node: block (prod: 111) at line 4, scope: 0x559f3a763590
DEBUG: Entering node: ifStatement (prod: 340) at line 4, scope: 0x559f3a763590
DEBUG: Entering node: BooleanLiteral (prod: 393) at line 2, scope: 0x559f3a763590
DEBUG: Entering node: true (prod: 393) at line 0, scope: 0x559f3a763590
DEBUG: Entering node: functionCall (prod: 122) at line 4, scope: 0x559f3a763590
DEBUG: Entering node: println (prod: 396) at line 0, scope: 0x559f3a763590
DEBUG: Entering node: expressionList (prod: 116) at line 3, scope: 0x559f3a763590
DEBUG: Entering node: StringLiteral (prod: 395) at line 3, scope: 0x559f3a763590
DEBUG: Entering node: "Missing braces" (prod: 395) at line 0, scope: 0x559f3a763590
No errors

PASS: tests/errors/lex_test39.kt
PASS: tests/errors/sem7.kt
PASS: tests/errors/lex_test19.kt
PASS: tests/errors/lex_test27.kt
PASS: tests/errors/lex_test25.kt
PASS: tests/errors/lex_test54.kt
PASS: tests/errors/lex_test4.kt
PASS: tests/errors/lex_test11.kt
PASS: tests/errors/lex_test21.kt
PASS: tests/errors/sem4.kt
FAIL: tests/errors/sem8.kt
Expected Error, but got:
Processing file: tests/errors/sem8.kt
DEBUG: Entering node: functionDeclaration (prod: 327) at line 3, scope: 0x5573e4d44200
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'main' has scope pointer: 0x5573e4d44200
DEBUG: Entering node: main (prod: 396) at line 0, scope: 0x5573e4d44200
DEBUG: Entering node: functionValueParameters (prod: 108) at line 1, scope: 0x5573e4d44200
DEBUG: Entering node: block (prod: 111) at line 3, scope: 0x5573e4d44200
DEBUG: Entering node: functionCall (prod: 122) at line 3, scope: 0x5573e4d44200
DEBUG: Entering node: println (prod: 396) at line 0, scope: 0x5573e4d44200
DEBUG: Entering node: expressionList (prod: 116) at line 2, scope: 0x5573e4d44200
DEBUG: Entering node: comparison (prod: 299) at line 2, scope: 0x5573e4d44200
DEBUG: Entering node: StringLiteral (prod: 395) at line 2, scope: 0x5573e4d44200
DEBUG: Entering node: "hi" (prod: 395) at line 0, scope: 0x5573e4d44200
DEBUG: Entering node: IntegerLiteral (prod: 389) at line 2, scope: 0x5573e4d44200
DEBUG: Entering node: 3 (prod: 389) at line 0, scope: 0x5573e4d44200
No errors

PASS: tests/errors/lex_test13.kt
PASS: tests/errors/lex_test1.kt
PASS: tests/errors/lex_test22.kt
PASS: tests/errors/lex_test26.kt
PASS: tests/errors/lex_test24.kt
PASS: tests/errors/sem3.kt
PASS: tests/errors/lex_test51.kt
PASS: tests/errors/lex.kt
PASS: tests/errors/lex_test18.kt
PASS: tests/errors/lex_test0.kt
PASS: tests/errors/lex_test46.kt
PASS: tests/errors/lex_test36.kt
PASS: tests/errors/lex_test47.kt
PASS: tests/errors/sem.kt
PASS: tests/errors/lex_test49.kt
PASS: tests/errors/lex_test45.kt
PASS: tests/errors/lex_test20.kt
PASS: tests/errors/lex_test23.kt
PASS: tests/errors/lex_test48.kt
PASS: tests/errors/lex_test32.kt
FAIL: tests/errors/sem9.kt
Expected Error, but got:
Processing file: tests/errors/sem9.kt
DEBUG: Entering node: functionDeclaration (prod: 327) at line 4, scope: 0x5600a0665330
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'main' has scope pointer: 0x5600a0665330
DEBUG: Entering node: main (prod: 396) at line 0, scope: 0x5600a0665330
DEBUG: Entering node: functionValueParameters (prod: 108) at line 1, scope: 0x5600a0665330
DEBUG: Entering node: block (prod: 111) at line 4, scope: 0x5600a0665330
DEBUG: Entering node: assignment (prod: 280) at line 4, scope: 0x5600a0665330
DEBUG: Entering node: variableDeclaration (prod: 329) at line 4, scope: 0x5600a0665330
DEBUG: Entering node: z (prod: 396) at line 0, scope: 0x5600a0665330
DEBUG: Entering node: functionCall (prod: 122) at line 4, scope: 0x5600a0665330
DEBUG: Entering node: undeclaredFunction (prod: 396) at line 0, scope: 0x5600a0665330
DEBUG: Entering node: expressionList (prod: 116) at line 2, scope: 0x5600a0665330
DEBUG: Entering node: IntegerLiteral (prod: 389) at line 2, scope: 0x5600a0665330
DEBUG: Entering node: 3 (prod: 389) at line 0, scope: 0x5600a0665330
No errors

PASS: tests/errors/lex_test37.kt
PASS: tests/errors/lex_test29.kt
PASS: tests/errors/syn4.kt
PASS: tests/errors/lex_test33.kt
PASS: tests/errors/syn5.kt
PASS: tests/errors/lex_test16.kt
PASS: tests/errors/lex_test52.kt
PASS: tests/errors/lex_test6.kt
PASS: tests/errors/lex_test7.kt
PASS: tests/errors/sem10.kt
PASS: tests/errors/lex_test40.kt
PASS: tests/errors/lex_test28.kt
PASS: tests/errors/lex_test8.kt
PASS: tests/errors/sem6.kt
PASS: tests/errors/lex_test55.kt
PASS: tests/errors/lex_test30.kt
PASS: tests/errors/sem5.kt
PASS: tests/errors/lex_test14.kt
PASS: tests/errors/lex_test31.kt
PASS: tests/errors/lex_test17.kt
PASS: tests/errors/syn.kt
PASS: tests/errors/lex_test50.kt
PASS: tests/errors/lex_test3.kt
PASS: tests/errors/lex_test43.kt
PASS: tests/errors/lex_test44.kt
PASS: tests/errors/lex_test9.kt
PASS: tests/errors/lex_test2.kt
PASS: tests/errors/lex_test35.kt
PASS: tests/errors/lex_test34.kt
PASS: tests/errors/sem2.kt
PASS: tests/errors/lex_test38.kt
PASS: tests/errors/lex_test10.kt
PASS: tests/errors/lex_test41.kt
PASS: tests/errors/lex_test15.kt
PASS: tests/errors/lex_test5.kt
FAIL: tests/k0/syn1.kt
Expected No Error, but got:

Error #1 at line 1: syntax error
Near token: 'val'
Line 1: val globalVal: Int = 42
       ^
Hint: Check for missing semicolons, brackets, or incorrect token ordering

FAIL: tests/k0/syn_hellowrld.kt
Expected No Error, but got:
Semantic Error at line 8: Operator operands have incompatible types
Semantic Error at line 0: Assignment to immutable variable
Semantic Error at line 9: Type mismatch in assignment: cannot assign value of type float to variable of type none
Semantic Error at line 9: Operator operands have incompatible types
Semantic Error at line 0: Assignment to immutable variable
Semantic Error at line 10: Type mismatch in assignment: cannot assign value of type float to variable of type none

Parsing completed with 6 semantic error(s)

FAIL: tests/k0/sem1.kt
Expected No Error, but got:

Error #1 at line 53: syntax error
Near token: '{'
Line 53:    val data: Array<Int> = Array<Int>(4) { 0 }
        ^
Hint: Check for missing semicolons, brackets, or incorrect token ordering

PASS: tests/k0/syn_multiply.kt
FAIL: tests/k0/lex_test1.kt
Expected No Error, but got:
Semantic Error at line 64: Operator operands have incompatible types
Semantic Error at line 65: Type mismatch in declaration: cannot assign value of type float to variable of type int
Semantic Error at line 65: Operator operands have incompatible types
Semantic Error at line 66: Type mismatch in declaration: cannot assign value of type float to variable of type int
Semantic Error at line 66: Operator operands have incompatible types
Semantic Error at line 67: Operator operands have incompatible types
Semantic Error at line 68: Operator operands have incompatible types
Semantic Error at line 101: Type mismatch in declaration: cannot assign value of type none to variable of type string
Semantic Error at line 111: Type mismatch in declaration: cannot assign value of type none to variable of type int
Semantic Error at line 113: Type mismatch in declaration: cannot assign value of type none to variable of type int
Semantic Error at line 118: Operator operands have incompatible types
Semantic Error at line 118: Operator operands have incompatible types
Semantic Error at line 119: Type mismatch in declaration: cannot assign value of type float to variable of type int

Parsing completed with 13 semantic error(s)

FAIL: tests/k0/sem_test1.kt
Expected No Error, but got:
Semantic Error at line 9: Operator operands have incompatible types
Semantic Error at line 0: Assignment to immutable variable
Semantic Error at line 10: Type mismatch in assignment: cannot assign value of type float to variable of type none
Semantic Error at line 14: Operator operands have incompatible types
Semantic Error at line 0: Assignment to immutable variable
Semantic Error at line 15: Type mismatch in assignment: cannot assign value of type float to variable of type none

Parsing completed with 6 semantic error(s)

FAIL: tests/k0/syn_while.kt
Expected No Error, but got:
Semantic Error at line 5: Operator operands have incompatible types
Semantic Error at line 0: Assignment to immutable variable
Semantic Error at line 5: Type mismatch in assignment: cannot assign value of type float to variable of type none

Parsing completed with 3 semantic error(s)

FAIL: tests/k0/syn_test1.kt
Expected No Error, but got:
Semantic Error at line 12: Operator operands have incompatible types
Semantic Error at line 0: Assignment to immutable variable
Semantic Error at line 14: Type mismatch in assignment: cannot assign value of type float to variable of type none
Semantic Error at line 31: Operator operands have incompatible types
Semantic Error at line 0: Assignment to immutable variable
Semantic Error at line 32: Type mismatch in assignment: cannot assign value of type float to variable of type none
Semantic Error at line 51: Operator operands have incompatible types
Semantic Error at line 63: Operator operands have incompatible types
Semantic Error at line 67: Operator operands have incompatible types

Parsing completed with 9 semantic error(s)

PASS: tests/kotlin/syn7.kt
PASS: tests/kotlin/lex_test42.kt
PASS: tests/kotlin/lex_test12.kt
PASS: tests/kotlin/syn2.kt
PASS: tests/kotlin/syn3.kt
PASS: tests/kotlin/lex_test53.kt
PASS: tests/kotlin/syn6.kt
PASS: tests/kotlin/lex_test39.kt
PASS: tests/kotlin/sem7.kt
PASS: tests/kotlin/lex_test19.kt
PASS: tests/kotlin/lex_test27.kt
PASS: tests/kotlin/lex_test25.kt
PASS: tests/kotlin/lex_test54.kt
PASS: tests/kotlin/syn1.kt
PASS: tests/kotlin/lex_test4.kt
PASS: tests/kotlin/lex_test11.kt
PASS: tests/kotlin/sem1.kt
PASS: tests/kotlin/lex_test21.kt
PASS: tests/kotlin/sem4.kt
PASS: tests/kotlin/lex_test13.kt
PASS: tests/kotlin/lex_test1.kt
PASS: tests/kotlin/lex_test22.kt
PASS: tests/kotlin/lex_test26.kt
PASS: tests/kotlin/lex_test24.kt
PASS: tests/kotlin/sem3.kt
PASS: tests/kotlin/lex_test51.kt
PASS: tests/kotlin/lex_test18.kt
PASS: tests/kotlin/lex_test0.kt
PASS: tests/kotlin/lex_test46.kt
PASS: tests/kotlin/lex_test36.kt
PASS: tests/kotlin/lex_test47.kt
PASS: tests/kotlin/lex_test49.kt
PASS: tests/kotlin/lex_test45.kt
PASS: tests/kotlin/lex_test20.kt
PASS: tests/kotlin/lex_test23.kt
PASS: tests/kotlin/lex_test48.kt
PASS: tests/kotlin/lex_test32.kt
PASS: tests/kotlin/lex_test37.kt
PASS: tests/kotlin/lex_test29.kt
PASS: tests/kotlin/syn4.kt
PASS: tests/kotlin/lex_test33.kt
FAIL: tests/kotlin/syn5.kt
Expected Error, but got:
Processing file: tests/kotlin/syn5.kt
DEBUG: Entering node: functionDeclaration (prod: 327) at line 5, scope: 0x5600af7ab580
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'main' has scope pointer: 0x5600af7ab580
DEBUG: Entering node: main (prod: 396) at line 0, scope: 0x5600af7ab580
DEBUG: Entering node: functionValueParameters (prod: 108) at line 1, scope: 0x5600af7ab580
DEBUG: Entering node: block (prod: 111) at line 5, scope: 0x5600af7ab580
DEBUG: Entering node: statements (prod: 112) at line 5, scope: 0x5600af7ab580
DEBUG: Entering node: assignment (prod: 280) at line 3, scope: 0x5600af7ab580
DEBUG: Entering node: variableDeclaration (prod: 329) at line 3, scope: 0x5600af7ab580
DEBUG: Entering node: a (prod: 396) at line 0, scope: 0x5600af7ab580
DEBUG: Entering node: type (prod: 102) at line 2, scope: 0x5600af7ab580
DEBUG: Entering node: Int (prod: 396) at line 0, scope: 0x5600af7ab580
DEBUG: Entering node: IntegerLiteral (prod: 389) at line 2, scope: 0x5600af7ab580
DEBUG: Entering node: 5 (prod: 389) at line 0, scope: 0x5600af7ab580
DEBUG: Entering node: ifStatement (prod: 340) at line 5, scope: 0x5600af7ab580
DEBUG: Entering node: comparison (prod: 298) at line 3, scope: 0x5600af7ab580
DEBUG: Entering node: Identifier (prod: 396) at line 3, scope: 0x5600af7ab580
DEBUG: Entering node: a (prod: 396) at line 0, scope: 0x5600af7ab580
DEBUG: Entering node: IntegerLiteral (prod: 389) at line 3, scope: 0x5600af7ab580
DEBUG: Entering node: 6 (prod: 389) at line 0, scope: 0x5600af7ab580
DEBUG: Entering node: functionCall (prod: 122) at line 5, scope: 0x5600af7ab580
DEBUG: Entering node: println (prod: 396) at line 0, scope: 0x5600af7ab580
DEBUG: Entering node: expressionList (prod: 116) at line 4, scope: 0x5600af7ab580
DEBUG: Entering node: StringLiteral (prod: 395) at line 4, scope: 0x5600af7ab580
DEBUG: Entering node: "less" (prod: 395) at line 0, scope: 0x5600af7ab580
No errors

PASS: tests/kotlin/lex_test16.kt
PASS: tests/kotlin/lex_test52.kt
PASS: tests/kotlin/lex_test6.kt
PASS: tests/kotlin/lex_test7.kt
PASS: tests/kotlin/lex_test40.kt
PASS: tests/kotlin/lex_test28.kt
PASS: tests/kotlin/lex_test8.kt
PASS: tests/kotlin/sem6.kt
PASS: tests/kotlin/lex_test55.kt
PASS: tests/kotlin/lex_test30.kt
PASS: tests/kotlin/sem5.kt
PASS: tests/kotlin/lex_test14.kt
PASS: tests/kotlin/lex_test31.kt
PASS: tests/kotlin/lex_test17.kt
PASS: tests/kotlin/lex_test50.kt
PASS: tests/kotlin/lex_test3.kt
PASS: tests/kotlin/lex_test43.kt
PASS: tests/kotlin/lex_test44.kt
PASS: tests/kotlin/lex_test9.kt
PASS: tests/kotlin/lex_test2.kt
PASS: tests/kotlin/lex_test35.kt
PASS: tests/kotlin/lex_test34.kt
FAIL: tests/kotlin/sem2.kt
Expected Error, but got:
Processing file: tests/kotlin/sem2.kt
DEBUG: Entering node: topLevelObjectList (prod: 101) at line 9, scope: 0x5626025547a0
DEBUG: Entering node: functionDeclaration (prod: 327) at line 6, scope: 0x5626025547a0
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'fun1' has scope pointer: 0x562602554220
DEBUG: Entering node: fun1 (prod: 396) at line 0, scope: 0x562602554220
DEBUG: Entering node: functionValueParameters (prod: 108) at line 1, scope: 0x562602554220
DEBUG: Entering node: block (prod: 111) at line 6, scope: 0x562602554220
DEBUG: Entering node: statements (prod: 112) at line 6, scope: 0x562602554220
DEBUG: Entering node: functionDeclaration (prod: 327) at line 4, scope: 0x562602554220
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'fun2' has scope pointer: 0x5626025544e0
DEBUG: Entering node: fun2 (prod: 396) at line 0, scope: 0x5626025544e0
DEBUG: Entering node: functionValueParameters (prod: 108) at line 2, scope: 0x5626025544e0
DEBUG: Entering node: block (prod: 111) at line 4, scope: 0x5626025544e0
DEBUG: Entering node: functionCall (prod: 122) at line 4, scope: 0x5626025544e0
DEBUG: Entering node: println (prod: 396) at line 0, scope: 0x5626025544e0
DEBUG: Entering node: expressionList (prod: 116) at line 3, scope: 0x5626025544e0
DEBUG: Entering node: StringLiteral (prod: 395) at line 3, scope: 0x5626025544e0
DEBUG: Entering node: "nested function" (prod: 395) at line 0, scope: 0x5626025544e0
DEBUG: Entering node: functionCall (prod: 122) at line 6, scope: 0x562602554220
DEBUG: Entering node: fun2 (prod: 396) at line 0, scope: 0x562602554220
DEBUG: Entering node: functionDeclaration (prod: 327) at line 9, scope: 0x5626025547a0
DEBUG: Function declaration encountered. Updating current scope.
DEBUG: Function 'main' has scope pointer: 0x5626025547a0
DEBUG: Entering node: main (prod: 396) at line 0, scope: 0x5626025547a0
DEBUG: Entering node: functionValueParameters (prod: 108) at line 7, scope: 0x5626025547a0
DEBUG: Entering node: block (prod: 111) at line 9, scope: 0x5626025547a0
DEBUG: Entering node: functionCall (prod: 122) at line 9, scope: 0x5626025547a0
DEBUG: Entering node: fun1 (prod: 396) at line 0, scope: 0x5626025547a0
No errors

PASS: tests/kotlin/lex_test38.kt
PASS: tests/kotlin/lex_test10.kt
PASS: tests/kotlin/lex_test41.kt
PASS: tests/kotlin/lex_test15.kt
PASS: tests/kotlin/lex_test5.kt

=== TEST SUMMARY ===
Total Tests: 153
Passed: 140
Failed: 13
